server:
  port: 8080

spring:
  application:
    name: view
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: view
#<<< EDA / Topic Name
          destination: untitled
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: untitled
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    root: ${VIEW_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${VIEW_LOG_LEVEL}
      springframework:
        cloud: ${VIEW_LOG_LEVEL}


server:
  port: 8085

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: view
          destination: bookrental
          contentType: application/json
        event-out:
          destination: bookrental
          contentType: application/json

logging:
  level:
    root: ${VIEW_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${VIEW_LOG_LEVEL}
      springframework:
        cloud: ${VIEW_LOG_LEVEL}

